# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven Wrapper
        run: ./mvnw -B package
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag nabla/petclinic-native:${{ github.sha }}
      - name: Tag the Docker image to latest
        run: docker tag nabla/petclinic-native:${{ github.sha }} nabla/petclinic-native:latest
      - name: Tag the Docker image to date
        run: docker tag nabla/petclinic-native:${{ github.sha }} nabla/petclinic-native:$(date +%s)

      #- name: Run Trivy vulnerability scanner
      #  uses: aquasecurity/trivy-action@master
      #  with:
      #    image-ref: 'docker.io/nabla/petclinic-native:${{ github.sha }}'
      #    format: 'table'
      #    exit-code: '1'
      #    ignore-unfixed: true
      #    vuln-type: 'os,library'
      #    severity: 'CRITICAL,HIGH'

      #- name: Push the Docker image
      #  run: docker push nabla/petclinic-native:latest

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nabla/petclinic-native
          add_git_labels: true
          tags: latest
          tag_with_ref: true
          tag_with_sha: true
